services:

  # O NOVO MOTOR: PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: financas-postgres
    restart: unless-stopped
    ports:
      - "5433:5432" # A porta padrão universal do Postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: financas
    volumes:
      - financas_pg_data:/var/lib/postgresql/data

  # 1. Banco de Dados MySQL
  # db:
  #   image: mysql:8.0
  #   container_name: financas-mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: controle_financas
  #   ports:
  #     - "3308:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  # 2. API Node.js (Backend)
  api:
    build: ./backend 
    container_name: financas-api
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - db # O Backend só liga DEPOIS que o banco de dados estiver pronto
    environment:
      # O Segredo da Nuvem: O Backend agora fala com o "db" em vez de "localhost"
      - DATABASE_URL=postgresql://root:root@db:5432/financas?schema=public

  # 3. A Tela React (Frontend)
  web:
    build: ./frontend # Procura o Dockerfile na pasta do frontend
    container_name: financas-web
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - api # O Frontend só liga DEPOIS que a API estiver pronta
    # Opcional mas recomendado: Mapeamos a pasta src para não perdermos o "Hot Reload"
    volumes:
      - ./frontend/src:/app/src

volumes:
  #mysql_data:
  financas_pg_data:
